### ISSUE TITLE
usbtreeview@4.4.3: hash check failed

### ISSUE THREAD

**Issue by kyonmiriam** [rasa/scoops#101]
console output:
App:         rasa/usbtreeview
URL:         https://www.uwe-sieber.de/files/UsbTreeView_x64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    558620110d614a0859d08550c9d0259c2cabc7d8444dc8df43754a64380b85d4
Actual:      96664ad2dba9cdcdc55fbf98e189505ac59e69a81294ae614bf1ccf59b058756

**Comment by rasa** [comment]
Fixed in https://github.com/rasa/scoops/commit/4f985043c4684e91209c127eadadd30bb02b02eb
