### ISSUE TITLE
tom's hash-explorer address have changed

### ISSUE THREAD

**Issue by K-mikaZ** [rasa/scoops#14]
Please considering the new address for [tom's hash-explorer]( https://www.mannerud.org/tom-andreas/software/toms-hash-explorer/)

**Comment by rasa** [comment]
Sorry, nothing appears to have changed. Can you be more specific?

**Comment by K-mikaZ** [comment]
An error on my part, sorry for the inconvenience

**Comment by rasa** [comment]
No worries!
