### ISSUE TITLE
babelpad@12.1.0.4: hash check failed

### ISSUE THREAD

**Issue by teddue** [rasa/scoops#17]
Checking hash of BabelPad.zip ... ERROR Hash check failed!
App:         rasa/babelpad
URL:         http://www.babelstone.co.uk/Software/Download/BabelPad.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    9356750824b9b81e84068c98f5df8bb9502355f7241148110d409080a2b275d3
Actual:      5875ad719e0982e7a6bd21e90cfde779866c0d8dc27041108c823516bd310d11

**Comment by rasa** [comment]
Fixed in https://github.com/rasa/scoops/commit/17e8879b00034859aa552f38df3402228b5ea1a5
