### ISSUE TITLE
cpdf@2.3.1: hash check failed

### ISSUE THREAD

**Issue by niheaven** [rasa/scoops#22]
App:         rasa/cpdf
URL:         https://github.com/coherentgraphics/cpdf-binaries/raw/master/Windows/cpdf.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    5c6025434adcc95b6cd558fc6dd412352d57b04c1d4839078c056c6491eed8c3
Actual:      c21d898fec5fd8d30c2b512fc64cb7d81edb95679445b5efbff5447a7edb42b7

The Actual one is correct.

**Comment by rasa** [comment]
@niheaven Thanks for the report. Sorry it took so long to fix.
