### ISSUE TITLE
babelpad@13.0.0.7: hash check failed

### ISSUE THREAD

**Issue by teddue** [rasa/scoops#26]
Installing 'babelpad' (13.0.0.7) [64bit]
Starting download with aria2 ...
Download: [#554d37 2.3MiB/5.9MiB(40%) CN:1 DL:7.5MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 554d37|OK  |   9.0MiB/s|C:/Users/teddue/scoop/cache/babelpad#13.0.0.7#http_www.babelstone.co.uk_Software_Download_BabelPad.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of BabelPad.zip ... ERROR Hash check failed!
App:         rasa/babelpad
URL:         http://www.babelstone.co.uk/Software/Download/BabelPad.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    cdff383adb345bd6febdefd0dde276f277f3e6f7a9fd5cbf25029ba3ed8221ff
Actual:      82c0f9e7ad2295ad51d44a4b93e31b18fae3e46fa6e6d8eca40a464824510082

**Comment by rasa** [comment]
Fixed in https://github.com/rasa/scoops/commit/8dab51e8336a58bca2c36cf78de3733f02671ff6
