### ISSUE TITLE
ntttcp@5.33: decompress error

### ISSUE THREAD

**Issue by tan-wei** [rasa/scoops#33]
Checking hash of NTttcp-v5.33.zip ... ok.
Extracting NTttcp-v5.33.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Winterreise\scoop\apps\ntttcp\5.33\NTttcp-v5.33.zip.
Log file:
  ~\scoop\apps\ntttcp\5.33\7zip.log

Please try again or create a new issue by using the following link and paste your console output:

**Comment by tan-wei** [comment]
7zip.log:
```

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 20019 bytes (20 KiB)

Extracting archive: C:\Users\Winterreise\scoop\apps\ntttcp\5.33\NTttcp-v5.33.zip

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
```

**Comment by tan-wei** [comment]
`scoop rm cache ntttcp` and retry does not work, either.

**Comment by rasa** [comment]
Thanks for the report. 5.33's [URL](https://gallery.technet.microsoft.com/NTttcp-Version-528-Now-f8b12769/file/159655/1/NTttcp-v5.33.zip) is gone. I will replace 5.33 with 5.35 found at https://github.com/microsoft/ntttcp/releases/download/v5.35/NTttcp.exe
