### ISSUE TITLE
fastcopy switched to installer in 3.50

### ISSUE THREAD

**Issue by jjaarrvviiss** [rasa/scoops#7]
Turns out fastcopy is now an installer as of 3.50 ... I wonder if it's inno or another installer type?

https://fastcopy.jp/help/fastcopy_eng.htm#history

**Comment by jjaarrvviiss** [comment]
fails at `Can't shim 'FastCopy.exe': File doesn't exist.`

**Comment by rasa** [comment]
Thanks for the heads up. I'm on it.

**Comment by rasa** [comment]
See https://groups.google.com/d/msg/fastcopy-bb-eng/T-MUfwcPRxA/o0ImagGQBQAJ

**Comment by rasa** [comment]
I disabled fastcopy for now in https://github.com/rasa/scoops/commit/fa84cc46068b20dbd647a3b4ca9e551e199f7179

**Comment by jjaarrvviiss** [comment]
fastcopy 3.52 has been released with /SILENT option!

**Comment by jjaarrvviiss** [comment]
![capture](https://user-images.githubusercontent.com/39548838/43041324-c0c9c48c-8d11-11e8-9118-18dab9907b06.PNG)

**Comment by rasa** [comment]
@jjaarrvviiss Thanks for the heads up!
