### ISSUE TITLE
wfc@6.9.9.9: hash check failed

### ISSUE THREAD

**Issue by Esentries** [rasa/scoops#76]
ERROR Hash check failed!
App:         rasa_scoops/wfc
URL:         https://www.binisoft.org/download/wfc6setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    1fb0168f191aed283022a4c6614f8f2ab2e3db087ae315c9083760638e8e530f
Actual:      16442002148e25cc009ad69e6292ce763eeb93108a9008c35019ec2ca7252f32

**Comment by rasa** [comment]
Fixed in #77. Thx for the report!
